Sarif Industries/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sarif_Industries.Data_Access_Layer;
using Sarif_Industries.Models;
using Sarif_Industries.View_Models;
using System.Globalization;
using Sarif_Industries.PartialModels;

namespace Sarif_Industries.Controllers
{
    public class CartsController : ApplicationController
    {


        // GET: Carts
        public ActionResult Cart()
        {
            return View();
        }

        public JsonResult AddToCart([Bind(Include = "cartId,UserId,ProductId,Colour,Quantity,Price")] Cart cart)
        {

            bool result = false;
            int userId = Convert.ToInt32(Session["UserId"]);

            if (ModelState.IsValid)
            {
                if (Session["UserId"] != null)
                {
                    Cart_PM.AddToCartDb(cart, userId);
                    result = true;

                }
                else
                {
                    Cart_PM.AddtoCartSession(cart);
                    result = true;
                }

            }

            return Json(result);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Cart cart = new Cart();
            ShoppingCart shoppingCart = new ShoppingCart();


            // get cart either by session or from database
            if (Session[UserIDKey] != null)
                cart = ModelContext.Carts.Find(id);
            else
            {
                int index = id.GetValueOrDefault();
                cart = Cart_PM.GetCart().ElementAt(index);

                shoppingCart.CartSessionIndex = index;
            }


            if (cart == null)
            {
                return HttpNotFound();
            }
            else
            {

                shoppingCart.Cart = cart;

                shoppingCart.Product = ModelContext.Products.Where(p => p.ProductId == cart.ProductId).SingleOrDefault();

                shoppingCart.ProductColours = (from d in ModelContext.ProductColours
                                               join f in ModelContext.ProductImages
                                               on d.ColourId equals f.ColourId
                                               where f.ProductId == cart.ProductId
                                               select d).Distinct();

                shoppingCart.ProductImages = ModelContext.ProductImages
                    .Where(p => p.ProductId == cart.ProductId)
                    .ToList();

                return View(shoppingCart);
            }

        }

        // POST: Carts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cartId,UserId,ProductId,Colour,Quantity,Price")] Cart cart)
        {
            int userId = Convert.ToInt32(Session["UserId"]);

            if (Session[UserIDKey] != null)
            {
                if (ModelState.IsValid)
                {
                    cart.UserId = userId;

                    ModelContext.Entry(cart).State = EntityState.Modified;
                    ModelContext.SaveChanges();
                    return RedirectToAction("Cart");
                }
            }

            return View(cart);
        }

        public JsonResult EditCartSession([Bind(Include = "cartId,UserId,ProductId,Colour,Quantity,Price")] Cart cart, int id)
        {

            bool result = false;

            if (Session[CartSessionKey] != null)
            {
                Cart_PM.EditCartSession(cart, id);
                result = true;
            }

            return Json(result);
        }


        public ActionResult Checkout()
        {
            Checkout checkout = new Checkout();
            int userId = Convert.ToInt32(Session["UserId"]);

            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Users");
            }

            var items = ModelContext.Carts
                .Where(c => c.UserId == userId)
                .Count();

            // redirect to carts page if no items in shopping cart
            if (items <= 0)
            {
                return RedirectToAction("Cart");
            }

            checkout.User = ModelContext.Users.Find(userId);
            ViewBag.Forename = checkout.User.Forename;
            ViewBag.Surname = checkout.User.Surname;
            ViewBag.Address = checkout.User.Address;
            ViewBag.PostCode = checkout.User.PostCode;
            ViewBag.Phone = checkout.User.Phone;


            checkout.Cart = ModelContext.Carts
                    .Include(c => c.Product)
                    .Include(c => c.User)
                    .Where(c => c.UserId == userId)
                    .ToList();


            checkout.Orders = new List<Order> { new Order
                            {
                                FirstName = checkout.User.Forename,
                                LastName = checkout.User.Surname,
                                Address = checkout.User.Address,
                                Country = checkout.User.Country,
                                PostCode = checkout.User.PostCode
                            }};

            checkout.Product = (from d in ModelContext.Products
                                join f in ModelContext.Carts
                                on d.ProductId equals f.ProductId
                                select d).ToList();


            checkout.CountryList = Country_PM.GetCountries();




            return View(checkout);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Checkout(List<Order> orders)
        {
            int userId = Convert.ToInt32(Session["UserId"]);

            var product = (from d in ModelContext.Products
                           select d).ToList();

            var cart = ModelContext.Carts
                      .Where(c => c.UserId == userId)
                      .ToList();

            var user = ModelContext.Users.Find(userId);


            if (ModelState.IsValid)
            {
                foreach (var cartItem in cart)
                {
                    orders = new List<Order> { new Order
                    {
                        // add values to Orders table
                        UserId = UserIdSession,
                        ProductId = cartItem.ProductId,
                        Quantity = cartItem.Quantity,
                        Colour = cartItem.Colour,
                        Total = cartItem.Price,
                        FirstName = user.Forename,
                        LastName = user.Surname,
                        Address = user.Address,
                        Country = user.Country,
                        PostCode = user.PostCode,
                        OrderDate = DateTime.Now
                    } };

                    foreach (var prodItem in product)
                    {
                        if (prodItem.ProductId == cartItem.ProductId)
                        {
                            foreach (var order in orders)
                            {
                                ModelContext.Orders.Add(order);
                            }


                            // Update product stock
                            prodItem.Stock -= cartItem.Quantity;
                            ModelContext.Entry(prodItem).State = EntityState.Modified;

                            // remove product from Carts table
                            ModelContext.Carts.Remove(cartItem);

                        }
                    }
                }

                ModelContext.SaveChanges();
                ModelState.Clear();

                return RedirectToAction("Cart");
            }

            return View();
        }


        public JsonResult DeleteConfirmed(int id)
        {
            var cart = ModelContext.Carts
                .Where(x => x.ProductId == id && (x.UserId == UserIdSession))
                .SingleOrDefault();

            bool result = false;

            if (Session[UserIDKey] != null && cart != null)
            {
                ModelContext.Carts.Remove(cart);
                ModelContext.SaveChanges();
                result = true;
            }

            else if (Session[CartSessionKey] != null && cart != null)
            {
                Cart_PM.Remove(id);
                result = true;
            }

            return Json(result);
        }

        public ActionResult Order()
        {

            if (Session[UserIDKey] == null)
                return RedirectToAction("Login", "Users");

            AccountProfile accountProfile = new AccountProfile();

            accountProfile.User = ModelContext.Users
                .Where(u => u.UserId == UserIdSession).SingleOrDefault();

            accountProfile.Orders = ModelContext.Orders.Where(o => o.UserId == UserIdSession);

            accountProfile.Products = (from p in ModelContext.Products
                                       join o in ModelContext.Orders
                                       on p.ProductId equals o.ProductId
                                       select p);

            accountProfile.ProductImage = (from p in ModelContext.ProductImages
                                           join o in ModelContext.Orders
                                           on p.ProductId equals o.ProductId
                                           where p.IsDefaultImage == true
                                           select p);

            return View(accountProfile);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ModelContext.Dispose();

Sarif Industries/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sarif_Industries.Data_Access_Layer;
using Sarif_Industries.Models;
using Sarif_Industries.View_Models;
using Sarif_Industries.PartialModels;

namespace Sarif_Industries.Controllers
{
    public class ProductsController : ApplicationController
    {
        private ProductShop productShop = new ProductShop();


        // GET: Products
        public ActionResult Shop(string category, string searchString, string colour, string price)
        {

            Product_PM product_PM = new Product_PM();

            List<Product> products =  ModelContext.Products.Where (p => p.StateId != 3).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.Name.ToLower().Contains(searchString.ToLower())).ToList();
            }

            // Category filtering
            productShop.Product = product_PM.FilterCategory(products, category);

            // Colour filtering
            productShop.Product = product_PM.FilterColour(productShop.Product, colour);

            productShop.ProductCategories = ModelContext.ProductCategories;

            productShop.TotalCategoryCount = ModelContext.Products.Where(p => p.StateId != 3).Count();

            productShop.ProductColours = ModelContext.ProductColours;

            productShop.ProductSalePrice = (from d in ModelContext.ProductSales
                                            join f in ModelContext.Products
                                            on d.ProductId equals f.ProductId
                                            select d).ToList();

            productShop.ProductThumbnail = (from d in ModelContext.ProductImages
                                            join f in ModelContext.Products
                                            on d.ProductId equals f.ProductId
                                            where d.IsDefaultImage == true
                                            select d).ToList();


            // Create price sorting & range list
            productShop.PriceSort = product_PM.CreatePriceSort(productShop.PriceRange);
            productShop.PriceRange = product_PM.CreatePriceRange(productShop.PriceRange);

            // Price filtering
            productShop.Product = product_PM.FilterPrice(productShop.Product, price);

            productShop.SelectedPrice = !string.IsNullOrEmpty(price) ? "Price: " + price : "Price: All";
            productShop.SelectedCategory = !string.IsNullOrEmpty(category) ? "Category: " + category : "Category: All";
            productShop.SelectedColour = !string.IsNullOrEmpty(colour) ? "Colour: " + colour : "Colour: All";
            productShop.Search = !string.IsNullOrEmpty(searchString) ? "Searching: " + searchString : "Searching: All";


            return View(productShop);
        }

        public ActionResult Sale()
        {

            productShop.Product = ModelContext.Products.Where (p => p.StateId == 2).ToList();

            productShop.ProductSalePrice = (from s in ModelContext.ProductSales
                                            join p in ModelContext.Products
                                            on s.ProductId equals p.ProductId
                                            select s).ToList();

            productShop.ProductThumbnail = (from i in ModelContext.ProductImages
                                            join p in ModelContext.Products
                                            on i.ProductId equals p.ProductId
                                            where i.IsDefaultImage == true
                                            select i).ToList();

            return View(productShop);
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ProductDetail productDetail = new ProductDetail();

            // find product details by id
            productDetail.Product = ModelContext.Products.Find(id);

            productDetail.ProductCategory = (from d in ModelContext.ProductCategories
                                             join f in ModelContext.Products
                                             on d.CategoryId equals f.CategoryId
                                             where f.ProductId == id
                                             select d).SingleOrDefault();

            productDetail.ProductSalePrice = (from d in ModelContext.ProductSales
                                              join f in ModelContext.Products
                                              on d.ProductId equals f.ProductId
                                              where f.ProductId == id
                                              select d).ToList();

            // find the product images by id
            productDetail.ProductImages = ModelContext.ProductImages
                .Where(p => p.ProductId == id)
                .ToList();

            productDetail.ProductColours = (from d in ModelContext.ProductColours
                                            join f in ModelContext.ProductImages
                                            on d.ColourId equals f.ColourId
                                            where f.ProductId == id
                                            select d).Distinct();

            productDetail.Cart = new Cart();


            productDetail.Reviews = (from r in ModelContext.Reviews
                                     join p in ModelContext.Products
                                     on r.ProductId equals p.ProductId
                                     where p.ProductId == id
                                     select r).Distinct();

            productDetail.Review = new Review();

            productDetail.TotalReviews = productDetail.Reviews.Count();

            productDetail.Users = (from u in ModelContext.Users
                                   join r in ModelContext.Reviews
                                   on u.UserId equals r.UserId
                                   where u.UserId == r.UserId
                                   select u).Distinct();


            if (productDetail == null)
            {
                return HttpNotFound();
            }

            return View(productDetail);
        }

        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]
        public ActionResult AddReview([Bind(Include = "ReviewId,UserId,ProductId,Comment,ReviewDate")] Review review)
        {
            if (Session[UserIDKey] != null)
            {
                if (ModelState.IsValid)
                {
                    review.UserId = UserIdSession;
                    review.ReviewDate = DateTime.Now;

                    ModelContext.Reviews.Add(review);
                    ModelContext.SaveChanges();

                    return RedirectToAction("Details", new { id = review.ProductId });
                }
            }

            return RedirectToAction("Details", new { id = review.ProductId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ModelContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sarif Industries/Views/Shared/_BackToTop.cshtml
    <!-- Back to top -->
<div class="btn-back-to-top bg0-hov" id="myBtn">
    <span class="symbol-btn-back-to-top">
        <i class="fa fa-angle-double-up" aria-hidden="true"></i>
    </span>
</div>

Sarif Industries/Views/Shared/_CartMenu.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<div id="header-cart">


    @if ((int)ViewData["cartitemscount"] == 0)
    {
        <img src="~/Content/images/icons/icon-header-02.png" class="header-icon1 js-show-header-dropdown" alt="ICON">
    }
    else
    {
        <img src="~/Content/images/icons/icon-header-02-notempty.png" class="header-icon1 js-show-header-dropdown" alt="ICON">
    }


    <span class="header-icons-noti">@ViewData["cartitemscount"]</span>

    <div class="header-cart header-dropdown">

        <ul class="header-cart-wrapitem">
            <li id="shoppingcartempty">
                <div class="header-cart-item-txt">
                    <p>Shopping Cart is Empty</p>
                </div>
            </li>

            @if (ViewData["cart"] != null)
            {
                foreach (var cart in ViewData["cart"] as IEnumerable<Sarif_Industries.Models.Cart>)
                {
                    foreach (var product in ViewData["product"] as IEnumerable<Sarif_Industries.Models.Product>)
                    {
                        if (cart.ProductId == product.ProductId)
                        {
                            <li id="shoppingcartitems" class="header-cart-item">
                                @foreach (var thumbnail in ViewData["productImage"] as IEnumerable<Sarif_Industries.Models.ProductImage>)
                                {
                                    if (thumbnail.ProductId == cart.ProductId)
                                    {
                                        using (Html.BeginForm("DeleteConfirmed", "Carts", new { id = cart.ProductId }))
                                        {
                                            <div class="header-cart-item-img" onclick="DeleteItem(@cart.ProductId)">
                                                <img src="@thumbnail.FilePath" alt="IMG-PRODUCT">
                                            </div>
                                        }


                                    }
                                }

                                <div class="header-cart-item-txt">
                                    <a href="@Url.Action("Details", "Products", new { id = cart.ProductId })" class="header-cart-item-name">
                                        @product.Name
                                    </a>

                                    <span class="header-cart-item-info">
                                        @cart.Colour
                                    </span>

                                    <span class="header-cart-item-info">
                                        @cart.Quantity x £@cart.Price
                                    </span>
                                </div>
                            </li>
                        }
                    }
                }
            }

        </ul>

        <div id="carttotal" class="header-cart-total">
            Total: £@ViewData["grandtotal"]

            <input id="grand-total" type="hidden" value="@ViewData["grandtotal"]" />
        </div>

        <div class="header-cart-buttons">
            <div class="header-cart-wrapbtn">
                <!-- Button -->
                <a href="@Url.Action("Cart","Carts")" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                    View Cart
                </a>
            </div>

            <div id="checkoutbtn" class="header-cart-wrapbtn">
                <!-- Button -->
                <a href="@Url.Action("Checkout","Carts")" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                    Check Out
                </a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="~/Scripts/Cart.js"></script>
<script type="text/javascript" src="~/Scripts/CartMenu.js"></script>

Sarif Industries/Views/Shared/_Footer.cshtml
<footer class="bg6 p-t-45 p-b-43 p-l-45 p-r-45">
    <div class="flex-w p-b-90">
        <div class="w-size6 p-t-30 p-l-15 p-r-15 respon3">
            <h4 class="s-text12 p-b-30">
                GET IN TOUCH
            </h4>

            <div>
                <p class="s-text7 w-size27">
                    Any questions? Let us know in store at 8th floor, 379 Hudson St, New York, NY 10018 or call us on (+1) 96 716 6879
                </p>

                <div class="flex-m p-t-30">
                    <a href="#" class="fs-18 color1 p-r-20 fa fa-facebook"></a>
                    <a href="#" class="fs-18 color1 p-r-20 fa fa-instagram"></a>
                    <a href="#" class="fs-18 color1 p-r-20 fa fa-pinterest-p"></a>
                    <a href="#" class="fs-18 color1 p-r-20 fa fa-snapchat-ghost"></a>
                    <a href="#" class="fs-18 color1 p-r-20 fa fa-youtube-play"></a>
                </div>
            </div>
        </div>

        <div class="w-size7 p-t-30 p-l-15 p-r-15 respon4">
            <h4 class="s-text12 p-b-30">
                Categories
            </h4>

            <ul>

                @foreach (var category in ViewData["categories"] as IEnumerable<Sarif_Industries.Models.ProductCategory>)
                {
                    <li class="p-b-9">
                        <a href="@Url.Action("Shop","Products", new { category = @category.Category })" class="s-text7">
                            @category.Category
                        </a>
                    </li>
                }
            </ul>
        </div>

        <div class="w-size7 p-t-30 p-l-15 p-r-15 respon4">
            <h4 class="s-text12 p-b-30">
                Links
            </h4>

            <ul>
                <li class="p-b-9">
                    @Html.ActionLink("Home", "Index", "Home", "", new { @class = "s-text7" })

                </li>

                <li class="p-b-9">
                    @Html.ActionLink("Shop", "Shop", "Products", "", new { @class = "s-text7" })
                </li>

                <li class="p-b-9">
                    @Html.ActionLink("Sale", "Sale", "Products", "", new { @class = "s-text7" })
                </li>
            </ul>
        </div>

        <div class="w-size7 p-t-30 p-l-15 p-r-15 respon4">
            <h4 class="s-text12 p-b-30">
                Account
            </h4>

            <ul>
                <li class="p-b-9">
                    <a href="@Url.Action("UserProfile","Users")" class="s-text7">
                        Profile
                    </a>
                </li>

                <li class="p-b-9">
                    <a href="@Url.Action("Order","Carts")" class="s-text7">
                        Orders
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="t-center p-l-15 p-r-15">
        <a href="#">
            <img class="h-size2" src="~/Content/images/icons/paypal.png" alt="IMG-PAYPAL">
        </a>

        <a href="#">
            <img class="h-size2" src="~/Content/images/icons/visa.png" alt="IMG-VISA">
        </a>

        <a href="#">
            <img class="h-size2" src="~/Content/images/icons/mastercard.png" alt="IMG-MASTERCARD">
        </a>

        <a href="#">
            <img class="h-size2" src="~/Content/images/icons/express.png" alt="IMG-EXPRESS">
        </a>

        <a href="#">
            <img class="h-size2" src="~/Content/images/icons/discover.png" alt="IMG-DISCOVER">
        </a>

        <div class="t-center s-text8 p-t-20">
            Copyright © 2018 All rights reserved. | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
        </div>
    </div>
</footer>

Sarif Industries/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Sarif Industries</title>

    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Content/images/icons/favicon.png" />



    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar");
    @RenderBody()
    @Html.Partial("_Footer");


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>